version: 2.1

### It's a good practice to keep your commands at the top of the config file. In this project, you'll need at least 2 commands:

# commands:
#   destroy-environment:
#     description: Destroy backend and frontend cloudformation stacks given a workflow ID.
#     ...

#   revert-migration:
#     description: Revert the last migration if successfully run in the current workflow.
#     ...
executors:
  node:
    docker:
      - image: circleci/node:13.8.0
  python:
    docker:
      - image: python:3.9.0-alpine
  aws:
    docker:
      - image: amazon/aws-cli

jobs:
  # create-ansible-inventory:
  #   executor: node
  #   steps:
  #     - checkout
  #     - run:
  #         name: create default inventory file
  #         working_directory: ./.circleci/ansible
  #         command: echo [all] > inventory
  #     - run:
  #       name: append ec2 instances to inventory
  #       working_directory: ./.circleci/ansible
  #       command: |
  #         <<-EOT
  #           aws ec2 describe-instances \
  #           --query 'Reservations[*].Instances[*].PublicIpAddress' \
  #           --filters "Name=tag:project,Values=udacity" \
  #           --output text >> inventory \
  #           && cat inventory
  #         EOT
  #     - save_cache:
  #         paths:
  #           - .circleci/ansible
  #         key: ansible-content


  # deploy-infrastructure:
  #   executor: aws
  #   steps:
  #     - checkout
  #     - run:
  #         name: Deploy EC2 instance on AWS with aws cli
  #         working_directory: ./.circleci
  #         command: |
  #           cd files && \
  #           aws cloudformation deploy \
  #             --stack-name udapeople-ec2-instance \
  #             --template-file backend.yml \
  #             --parameter-overrides ID="udapeople" \
  #             --tags project=udapeople
  #     - run:
  #         name: Save EC2 IP address in ansible inventory file
  #         working_directory: ./.circleci
  #         command: |
  #           cd ansible && \
  #           aws ec2 describe-instances \
  #             --query 'Reservations[*].Instances[*].PublicIpAddress' \
  #             --filters "Name=tag:project,Values=udapeople" \
  #             --output text >> inventory && \
  #           cat inventory
  #     - save_cache:
  #         paths:
  #           - .circleci/ansible
  #         key: ansible-dependencies


  configure-infrastructure:
    executor: python
    steps:
      - checkout
      - restore_cache:
          key: ansible-dependencies
      - add_ssh_keys:
          fingerprints: ["06:55:19:5c:75:9c:0c:fa:5e:f0:ed:c4:2b:35:ec:76"]
      - run:
          name: Install dependencies
          working_directory: ./.circleci/ansible
          command: |
            apk add --update ansible
            ansible --version
      - run:
          name: Configure server
          working_directory: ./.circleci/ansible
          command: |
            pwd && \
            ls -la && \
            cat inventory && \
            ansible-playbook -i inventory deploy-server.yaml

#  run-migrations:

#  deploy-frontend:

#  deploy-backend:

#  smoke-test:
  smoke_test:
    executor: python
    steps:
      - run: apk add --update curl
      - run:
          name: smoke test.
          command: |
            URL="https://google.com/"
            if curl -s --head ${URL} # test if google.com exists
            then
              return 0
            else
              return 1
            fi

#  cloudfront-update:

workflows:
  default:
    jobs:
      - smoke_test
      # - deploy-infrastructure:
      #   filters:
      #     branches:
      #       only:
      #         - master
      # - configure-infrastructure:
      #     requires:
      #       - deploy-infrastructure
