version: 2.1

### It's a good practice to keep your commands at the top of the config file. In this project, you'll need at least 2 commands:

# commands:
#   destroy-environment:
#     description: Destroy backend and frontend cloudformation stacks given a workflow ID.
#     ...

#   revert-migration:
#     description: Revert the last migration if successfully run in the current workflow.
#     ...
executors:
  node:
    docker:
      - image: circleci/node:13.8.0
  python:
    docker:
      - image: python:3.9.0-alpine

jobs:
  install-backend-deps:
    executor: node
    steps:
      - checkout
      - run:
          name: npm install
          working_directory: ./backend
          command: ls -la && npm install
      - save_cache:
          paths:
            - backend/node_modules
          key: backend-deps

  install-frontend-deps:
   executor: node
   steps:
      - checkout
      - run:
          name: npm install
          working_directory: ./frontend
          command: ls -la && npm install
      - save_cache:
          paths:
            - frontend/node_modules
          key: frontend-deps-2

  build-backend:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: backend-deps
      - run:
          name: npm run build
          working_directory: ./backend
          command: npm run build

  build-frontend:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: frontend-deps-2
      - run:
          name: npm run build
          working_directory: ./frontend
          command: npm run build

  test-frontend:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: frontend-deps-2
      - run:
          name: install junit coverage reporter
          working_directory: ./frontend
          command: npm install jest-junit
      - run:
          name: npm test --ci --runInBand --reporters=default --reporters=jest-junit
          working_directory: ./frontend
          command: npm run test
          environment:
            JEST_JUNIT_OUTPUT_DIR: frontend/test-results
      - store_test_results:
          path: frontend/test-results
#  test-frontend:

#  est-backend:

#  can-frontend:

#  scan-backend:

#  deploy-infrastructure:

#  configure-infrastructure:

#  run-migrations:

#  deploy-frontend:

#  deploy-backend:

#  smoke-test:

#  cloudfront-update:

workflows:
  default:
    jobs:
      - install-backend-deps
      - install-frontend-deps

      - build-backend:
          requires:
            - install-backend-deps
      - build-frontend:
          requires:
            - install-frontend-deps
      - test-frontend:
          requires:
            -  build-frontend
